version: '3'

services:
  app:
    build: .
    container_name: cultivar-app
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - SECRET_KEY=change_this_to_a_secure_key
      - ISLEY_DB_DRIVER=sqlite
      - ISLEY_PORT=4200
      - DEBUG=false
